### ISSUE TITLE
valent doesn't start - "TLS support is not available"

### ISSUE THREAD

**Issue by colemickens** [andyholmes/valent#428]
### Current Behavior

```
❯ valent
20:12:10.1688                       GLib-GIO:    DEBUG: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
20:12:10.1700                       GLib-GIO:    DEBUG: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
20:12:10.1701                       GLib-GIO:    DEBUG: _g_io_module_get_default: Found default implementation dummy (GDummyTlsBackend) for ‘gio-tls-backend’
Failed to register: TLS support is not available
```

### Expected Behavior

valent starts

### Desktop

Other (please specify)

### Other Desktop

sway

### Operating System

nixos (nixos-unstable)

### Installed from

Distribution Package

### Version

1.0.0.alpha

### Devices

Valent (Desktop Linux)

**Comment by FedericoSchonborn** [comment]
Weird, @colemickens are you running GNOME Shell or is it another desktop environment?

**Comment by FedericoSchonborn** [comment]
Also, could you try using this command?

```shell
nix run github:FedericoSchonborn/nixpkgs/valent-unstable-2023-03-31#valent
```

**Comment by colemickens** [comment]
@FedericoSchonborn I'm using Sway. 

```
❯ nix run github:FedericoSchonborn/nixpkgs/valent-unstable-2023-03-31#valent
20:58:33.4075                       GLib-GIO:    DEBUG: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
20:58:33.4087                       GLib-GIO:    DEBUG: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
20:58:33.4087                       GLib-GIO:    DEBUG: _g_io_module_get_default: Found default implementation dummy (GDummyTlsBackend) for ‘gio-tls-backend’
Failed to register: TLS support is not available
```

**Comment by FedericoSchonborn** [comment]
Okay, I added `glib-networking` as Andy said, could you try that command again?

**Comment by colemickens** [comment]
I'm not sure how to break the nix cache and it seems to cache by branch. I shallow cloned that branch and got a new build.

It starts up at least, thank you. I'll give it a shot and see how it goes.

I'll close this out, assuming you'll chase with a nixpkgs pr. Thanks again for the fast turnaround!

**Comment by colemickens** [comment]
Ah, I see this is already a commit in the open nixpkgs PR. Thanks again everyone!
https://github.com/NixOS/nixpkgs/pull/224563/commits/b033a3614995a2f140c7e3dc7e1c338eb2fed95c
