### ISSUE TITLE
Sending files to iPhone doesn't work

### ISSUE THREAD

**Issue by kdwk** [andyholmes/valent#439]
### Current Behavior

Sending a file to iPhone results in the iPhone KDE Connect app making the 'received' sound, but nothing happens after.

### Expected Behavior

The file is received correctly by the KDE Connect app on iPhone

### Desktop

GNOME Shell

### Operating System

Fedora Silverblue 38

### Installed from

Nightly Flatpak

### Version

1.0.0.alpha

### Devices

KDE Connect (iOS)

**Comment by kdwk** [comment]
How can I get logs?

**Comment by andyholmes** [comment]
You're on Fedora, so you can try [GNOME Logs](https://flathub.org/apps/details/org.gnome.Logs) or `journalctl`.

**Comment by kdwk** [comment]
Gnome Logs is broken, and `journalctl -g "valent"` only seem to show messages from gnome-software about installing and updating the app.

**Comment by andyholmes** [comment]
If there's an error sending or receiving a file, there will be a notification and/or warning printed to the log. You'll have to find a way to get logs of what's happening or there's not much I can do :shrug:

**Comment by andyholmes** [comment]
Closing due to lack of information, feel free to re-open if you can gather logs of the error.

**Comment by ftgjhf** [comment]
Hi! I’m running the latest Linux Mint XFCE, and sending files to my iPhone doesn’t work. I see the file on the iOS KDE Connect app with 0/XX bytes transmitted, and it times out after a short amount of time.
How do I send logs? I’m a bit of a noob
