### ISSUE TITLE
Media restarts after phone call even if media was not stopped by phone call

### ISSUE THREAD

**Issue by schuelermine** [andyholmes/valent#480]
### Current Behavior

When I have a video paused in Firefox and a call ends, the video gets played back, even if the phone call did not interrupt the video.

### Expected Behavior

I would expect Valent to keep track of if a play action is necessary so that this does not happen.

### Desktop

GNOME Shell

### Operating System

NixOS unstable

### Installed from

Distribution Package

### Version

1.0.0.alpha

### Devices

KDE Connect (Android)

**Comment by andyholmes** [comment]
Thanks for reporting.

I think I remember something like this happening, either because the Android app behaves unexpectedly or I misread the expected behaviour. I'll have a look when I get a chance :slightly_smiling_face:
