### ISSUE TITLE
Not detecting the KDEConnect smartphone

### ISSUE THREAD

**Issue by K3rcus** [andyholmes/valent#504]
### Current Behavior

The app never goes past "Searching for device..." the "KDE connect" app on Android doesn't detect the app on PC either, both are on the same wifi network

### Expected Behavior

Is expected to detect the smartphone with the KDE app on 

### Desktop

XFCE

### Operating System

Fedora 38

### Installed from

Nightly Flatpak

### Version

1.0.0.alpha

### Devices

Valent (Desktop Linux)

### Logs

```shell
❯ flatpak run ca.andyholmes.Valent
01:43:52.3245                       GLib-GIO:    DEBUG: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
01:43:52.3265                       GLib-GIO:    DEBUG: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
01:43:52.3635                       GLib-GIO:    DEBUG: _g_io_module_get_default: Found default implementation keyfile (GKeyfileSettingsBackend) for ‘gsettings-backend’
01:43:52.3640                       GLib-GIO:    DEBUG: _g_io_module_get_default: Found default implementation gnutls (GTlsBackendGnutls) for ‘gio-tls-backend’

(valent:2): GLib-GObject-CRITICAL **: 01:43:52.365: ../gobject/gsignal.c:2778: instance '0x55aa2eab3ff0' has no handler with id '61'
```

**Comment by andyholmes** [comment]
Can you confirm that other clients *can* connect between the same machines (i.e. KDE Connect, GSConnect, etc)?

To be honest, these are almost always local networking problems, since the connection process is extremely straight-forward (and covered in automated testing).

Is there anything special about your network, firewalls, proxies, VPNs, Wi-Fi/LAN isolation on the router, etc? There is some applicable [Troubleshooting on the KDE Connect Wiki](https://userbase.kde.org/KDEConnect#Troubleshooting) you can look over to see if anything applies.

**Comment by K3rcus** [comment]
Now it works.

It was the Fedora firewall. I didn't think of it because it worked with GSConnect on Gnome Fedora, I guess GSConnect opens the necessary ports by itself?

In case anyone else needs it I used:

```
sudo firewall-cmd --permanent --zone=public --add-service=kdeconnect
sudo firewall-cmd --reload
```

Maybe that can be added somehow to Valent to open the ports by itself when needed?

Thank you for yor work!
Its great to have this on XFCE

**Comment by andyholmes** [comment]
Unfortunately applications can't request changes to the firewall, AFAIK. If installed as a system package it will install a firewalld configuration, but there's no portal for Flatpak applications yet.

There will be some in-application help eventually, but Valent's still changing its UI quite often so I haven't merged that yet.
