### ISSUE TITLE
Some translations filed are not valid

### ISSUE THREAD

**Issue by sky96111** [andyholmes/valent#518]
### Current Behavior

Some text are translated in language.po but not work in application.
like:
``Preference``->``Desktop Integration``->``all description under item``
``enter some device``->``three dots``->``Preferences and Unpair button``
...

### Expected Behavior

The translated text cam be displayed correctly

### Desktop

GNOME Shell

### Operating System

Fedora 38

### Installed from

Nightly Flatpak

### Version

1.0.0.alpha

### Screenshots

![screenshot](https://upload.cc/i1/2023/07/04/OBghQm.png)
![screenshot](https://upload.cc/i1/2023/07/04/AGwp7x.png)
![screenshot](https://upload.cc/i1/2023/07/04/AoTeYm.png)
![screenshot](https://upload.cc/i1/2023/07/04/4KYVcr.png)

**Comment by andyholmes** [comment]
Thanks for the report with screenshots. I think #520 fixes most of the problems.

The string like `_Share` are keyboard mnemonics, usually you toggle them with `Alt + <letter after underscore>`. I removed those from the menus for now, but the others can be translated like `_Share` => `发送 (S)` or you could just ignore the `_` and translate as `发送`.
