### ISSUE TITLE
Unable to connect to phone using Tailscale

### ISSUE THREAD

**Issue by 0xMRTT** [andyholmes/valent#546]
### Current Behavior

I'm using Tailscale on my phone and on my computer, it's a mesh network so there's an IP for the phone and one for the computer. I tried to add the IP of the computer in the mobile app but it still doesn't detect Valent. Tailscale detect that Valent is running but the mobile app doesn't detect Valent. If you need more informations tell me!

### Expected Behavior

I except the mobile app to detect valent and valent to detect the mobile app.

### Desktop

GNOME Shell

### Operating System

NixOS

### Installed from

Distribution Package

### Version

1.0.0.alpha

### Devices

KDE Connect (Android)

**Comment by andyholmes** [comment]
Sorry, I don't really know anything about how Tailscale works, but it sounds interesting and a good fit for KDE Connect!

One way or the other, KDE Connect uses UDP for discovery (even with the new DNS-SD support). Can you confirm that UDP packets are not blocked for ports 1716-1764 and/or 5353?

**Comment by 0xMRTT** [comment]
Any idea how can i check it ?

**Comment by andyholmes** [comment]
No idea :grimacing: I'm not sure how this technology works, maybe Wireshark?

**Comment by 0xMRTT** [comment]
Will try

**Comment by andyholmes** [comment]
Moving this to discussions, since it doesn't appear to be an issue with Valent's expected functionality.

If there's something special Valent *should* do, we can open a specific issue for that.
