### ISSUE TITLE
Does not find the device

### ISSUE THREAD

**Issue by dinhokusanagi** [andyholmes/valent#556]
### Current Behavior

Does not find the device to synchronize

### Expected Behavior

Connect to the device

### Desktop

GNOME Shell

### Other Desktop

Gnome

### Operating System

Fedora Silverblue 38

### Installed from

Nightly Flatpak

### Version

nightly

### Devices

KDE Connect (Android)

### Logs

```shell
[wellington@fedora ~]$ flatpak run ca.andyholmes.Valent
12:32:54.8871                       GLib-GIO:    DEBUG: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
12:32:54.9048                       GLib-GIO:    DEBUG: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
12:32:54.9789                       GLib-GIO:    DEBUG: _g_io_module_get_default: Found default implementation keyfile (GKeyfileSettingsBackend) for ‘gsettings-backend’
12:32:54.9797                       GLib-GIO:    DEBUG: _g_io_module_get_default: Found default implementation gnutls (GTlsBackendGnutls) for ‘gio-tls-backend’

(valent:2): GLib-GObject-CRITICAL **: 12:32:54.981: ../gobject/gsignal.c:2778: instance '0x55cde1184050' has no handler with id '51'
```

### Screenshots

![Captura de tela de 2023-09-04 12-35-24](https://github.com/andyholmes/valent/assets/43162113/095ba404-9238-45dc-accc-6d50df41a2f3)

**Comment by andyholmes** [comment]
Can you confirm ports 1716-1764 are open for UDP and TCP? This is very likely a networking issue, since the connection process is very straight-forward.

**Comment by dinhokusanagi** [comment]
Yes, it is open

**Comment by andyholmes** [comment]
That should be enough then. I would go through all the regular steps, checking router, Wi-Fi isolation, firewall, ensure the device can be pinged, etc.

**Comment by dinhokusanagi** [comment]
![Captura de tela de 2023-09-04 18-12-04](https://github.com/andyholmes/valent/assets/43162113/8a1b9831-c1f1-4ff2-afca-47db19f8af15)

GSConnecte works correctly, Valent should be working too

**Comment by andyholmes** [comment]
Are you also running GSConnect at the same time?

**Comment by dinhokusanagi** [comment]
I had deactivated to try to pair the Valent, as I couldn't succeed activated again

**Comment by andyholmes** [comment]
Okay, you need to make sure you actually stop the service, since GSConnect will reserve port 1716. If GSConnect is running, Valent won't be able to connect to other devices.

I would recommend you stop GSConnect and uninstall it if you plan on using Valent.

**Comment by dinhokusanagi** [comment]
You were correct, I disabled the pairing and the GSConnect extension ended the session and now it works correctly. Thanks for the help.
![Captura de tela de 2023-09-04 20-10-04](https://github.com/andyholmes/valent/assets/43162113/bf35eaa4-f73f-4b0f-8865-1c0551373f28)
