### ISSUE TITLE
Remote input not working

### ISSUE THREAD

**Issue by cauebs** [andyholmes/valent#587]
### Current Behavior

No input gets through to the desktop and this warning is shown for each stroke on the remote (phone).
`valent-xdp-input:  WARNING: remote_desktop_start_screencast_cb(): GDBus.Error:org.freedesktop.DBus.Error.Failed: Remote desktop session already started`

### Expected Behavior

Cursor moves with the the input strokes on the remote.

### Desktop

GNOME Shell

### Operating System

Fedora Silverblue 39

### Installed from

Nightly Flatpak

### Version

nightly

### Devices

KDE Connect (Android), Valent (Desktop Linux)

**Comment by valpackett** [comment]
For me the remote session starts and there are no warnings shown on the phone but still no input gets through (and the session doesn't terminate when I quit the input panel on the phone)

**Comment by ElonSatoshi** [comment]
Same issue here, using the nightly flatpak and gnome extension zip downloaded from https://valent.andyholmes.ca/
