### ISSUE TITLE
[MPRIS] enabling MPRIS media players plugin causes app to crash

### ISSUE THREAD

**Issue by rohmishra** [andyholmes/valent#595]
### Current Behavior

Enabling MPRIS integration crashes the app

### Expected Behavior

Controls for media playing on laptop is available on my phone

### Desktop

GNOME Shell

### Operating System

Fedora 39

### Installed from

Nightly Flatpak

### Version

1.0.0.alpha

### Devices

Valent (Desktop Linux)

### Plugins

MPRIS

### Logs

```shell
{
  "application" : {
    "id" : "ca.andyholmes.Valent",
    "version" : "1.0.0.alpha",
    "commit" : "da60c12"
  },
  "runtime" : {
    "os" : "GNOME 45 (Flatpak runtime)",
    "desktop" : "GNOME",
    "session" : "wayland",
    "environment" : "flatpak"
  },
  "plugins" : {
    "xdp" : true,
    "telephony" : true,
    "systemvolume" : true,
    "sms" : true,
    "share" : true,
    "sftp" : true,
    "runcommand" : true,
    "pulseaudio" : true,
    "presenter" : true,
    "ping" : true,
    "notification" : true,
    "mpris" : true,
    "mousepad" : true,
    "lock" : true,
    "libvalent-ui" : true,
    "libvalent-device" : true,
    "lan" : true,
    "gtk" : true,
    "gnome" : true,
    "findmyphone" : true,
    "fdo" : true,
    "eds" : true,
    "contacts" : true,
    "connectivity_report" : true,
    "clipboard" : true,
    "battery" : true
  }
}
21:22:03.0017                       GLib-GIO:    DEBUG: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
21:22:03.0107                       GLib-GIO:    DEBUG: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
21:22:03.0561                       GLib-GIO:    DEBUG: _g_io_module_get_default: Found default implementation keyfile (GKeyfileSettingsBackend) for ‘gsettings-backend’
21:22:03.0571                       GLib-GIO:    DEBUG: _g_io_module_get_default: Found default implementation gnutls (GTlsBackendGnutls) for ‘gio-tls-backend’
21:22:03.0584                       GLib-GIO:    DEBUG: _g_io_module_get_default: Found default implementation portal (GNetworkMonitorPortal) for ‘gio-network-monitor’
21:22:03.0586                       GLib-GIO:    DEBUG: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
21:22:03.1206                       GLib-GIO:    DEBUG: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
21:22:03.2276                      libportal:    DEBUG: calling background
21:22:16.4973              valent-mpris-impl: CRITICAL: valent_mpris_impl_export: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
```

### Screenshots

Permissions are reset to default:
![image](https://github.com/andyholmes/valent/assets/2221064/7c5c79cb-4a75-4628-bee5-955ce8a295cf)

MediaPlayer2 is allowed for talks:
![image](https://github.com/andyholmes/valent/assets/2221064/3c55433b-7445-4163-8b8a-df0e03429707)

**Comment by andyholmes** [comment]
Hi, did you happen to get a stack trace from e.g. `coredumptctl`?

**Comment by rohmishra** [comment]
I do have it. However, GitHub doesn't allow me to upload that on here. Not sure how I could share it with you?

**Comment by rohmishra** [comment]
Lets me upload with zip:
[valent_mpris.zip](https://github.com/andyholmes/valent/files/13324470/valent_mpris.zip)

**Comment by rohmishra** [comment]
I was able to fix it by:
1. Disabling MPRIS for my phone.
2. enabling MPRIS plugin from the global settings.
3. re-enabling MPRIS sync for my phone.

**Comment by andyholmes** [comment]
> Lets me upload with zip:

Ah, sorry I meant like stack trace from the core dump, which would tell me where the crash happened. If this is in Flatpak, you can use `flatpak-coredumpctl`:

```
$ coredumpctl list
...
Fri 2023-11-03 13:42:18 PDT   2671 1000 1000 SIGSEGV present  /app/bin/valent
$ flatpak-coredumpctl -m 2671 ca.andyholmes.Valent
```

**Comment by rohmishra** [comment]
Im guessing you mean this?

           PID: 1011276 (valent)
           UID: 1000 (rmishra)
           GID: 1000 (rmishra)
        Signal: 11 (SEGV)
     Timestamp: Wed 2023-11-08 21:28:26 EST (3 days ago)
  Command Line: /app/bin/valent --gapplication-service
    Executable: /app/bin/valent
 Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/app-flatpak-ca.andyholmes.Valent-1011262.scope
          Unit: user@1000.service
     User Unit: app-flatpak-ca.andyholmes.Valent-1011262.scope
         Slice: user-1000.slice
     Owner UID: 1000 (rmishra)
       Boot ID: 7d14c9f2ca9646ea91572117a3d04f5b
    Machine ID: ac88061541ee485b9bc655a84e3fba15
      Hostname: stormstar
       Storage: /var/lib/systemd/coredump/core.valent.1000.7d14c9f2ca9646ea91572117a3d04f5b.1011276.1699496906000000.zst (present)
  Size on Disk: 10.5M
       Message: Process 1011276 (valent) of user 1000 dumped core.
                
                Stack trace of thread 2:
                #0  0x0000559994d1ed8e n/a (/app/bin/valent + 0x46d8e)
                #1  0x0000559994d1ef67 n/a (/app/bin/valent + 0x46f67)
                #2  0x00007f3bc844f25a n/a (/app/lib/libvalent-1.so.1 + 0x2925a)
                #3  0x00007f3bc8443fd9 n/a (/app/lib/libvalent-1.so.1 + 0x1dfd9)
                #4  0x00007f3bc80fd6fb n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7800.1 + 0x1b6fb)
                #5  0x00007f3bc80fa652 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7800.1 + 0x18652)
                #6  0x00007f3bc81104af n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7800.1 + 0x2e4af)
                #7  0x00007f3bc81163c1 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7800.1 + 0x343c1)
                #8  0x00007f3bc8116483 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7800.1 + 0x34483)
                #9  0x00007f3bc8256863 n/a (/usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.7800.1 + 0x110863)
                #10 0x00007f3bc81d9979 n/a (/usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.7800.1 + 0x93979)
                #11 0x00007f3bc80fa652 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7800.1 + 0x18652)
                #12 0x00007f3bc810f7b3 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7800.1 + 0x2d7b3)
                #13 0x00007f3bc81163c1 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7800.1 + 0x343c1)
                #14 0x00007f3bc8116483 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7800.1 + 0x34483)
                #15 0x00007f3bc825636b n/a (/usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.7800.1 + 0x11036b)
                #16 0x00007f3bc8250fd6 n/a (/usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.7800.1 + 0x10afd6)
                #17 0x00007f3bc7ff735d n/a (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.7800.1 + 0x6235d)
                #18 0x00007f3bc8251128 n/a (/usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.7800.1 + 0x10b128)
                #19 0x00007f3bc824fbb8 n/a (/usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.7800.1 + 0x109bb8)
                #20 0x00007f3bc8251ba9 n/a (/usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.7800.1 + 0x10bba9)
                #21 0x00007f3bc8257499 n/a (/usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.7800.1 + 0x111499)
                #22 0x00007f3bc80fa43a n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7800.1 + 0x1843a)
                #23 0x00007f3bc810e96c n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7800.1 + 0x2c96c)
                #24 0x00007f3bc81103f1 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7800.1 + 0x2e3f1)
                #25 0x00007f3bc81163c1 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7800.1 + 0x343c1)
                #26 0x00007f3bc8116483 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7800.1 + 0x34483)
                #27 0x00007f3bc80fea94 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7800.1 + 0x1ca94)
                #28 0x00007f3bc8101c07 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7800.1 + 0x1fc07)
                #29 0x00007f3bc80fa43a n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7800.1 + 0x1843a)
                #30 0x00007f3bc810e96c n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7800.1 + 0x2c96c)
                #31 0x00007f3bc81103f1 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7800.1 + 0x2e3f1)
                #32 0x00007f3bc81163c1 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7800.1 + 0x343c1)
                #33 0x00007f3bc8116483 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7800.1 + 0x34483)
                #34 0x00007f3bc80fea94 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7800.1 + 0x1ca94)
                #35 0x00007f3bc8101c07 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7800.1 + 0x1fc07)
                #36 0x00007f3bc7848557 n/a (/usr/lib/x86_64-linux-gnu/libgtk-4.so.1.1200.3 + 0x248557)
                #37 0x00007f3bc7848945 n/a (/usr/lib/x86_64-linux-gnu/libgtk-4.so.1.1200.3 + 0x248945)
                #38 0x00007f3bc78a1155 n/a (/usr/lib/x86_64-linux-gnu/libgtk-4.so.1.1200.3 + 0x2a1155)
                #39 0x00007f3bc80fa43a n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7800.1 + 0x1843a)
                #40 0x00007f3bc810e96c n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7800.1 + 0x2c96c)
                #41 0x00007f3bc81103f1 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7800.1 + 0x2e3f1)
                #42 0x00007f3bc81163c1 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7800.1 + 0x343c1)
                #43 0x00007f3bc8116483 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.7800.1 + 0x34483)
                #44 0x00007f3bc7a9fe5d n/a (/usr/lib/x86_64-linux-gnu/libgtk-4.so.1.1200.3 + 0x49fe5d)
                #45 0x00007f3bc7aa0d11 n/a (/usr/lib/x86_64-linux-gnu/libgtk-4.so.1.1200.3 + 0x4a0d11)
                #46 0x00007f3bc7aa0e94 n/a (/usr/lib/x86_64-linux-gnu/libgtk-4.so.1.1200.3 + 0x4a0e94)
                #47 0x00007f3bc7ff6c3a n/a (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.7800.1 + 0x61c3a)
                #48 0x00007f3bc7ff3d47 n/a (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.7800.1 + 0x5ed47)
                #49 0x00007f3bc7ff5e57 n/a (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.7800.1 + 0x60e57)
                #50 0x00007f3bc7ff6513 n/a (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.7800.1 + 0x61513)
                #51 0x00007f3bc823db1d n/a (/usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.7800.1 + 0xf7b1d)
                #52 0x0000559994d0530c n/a (/app/bin/valent + 0x2d30c)
                #53 0x00007f3bc6e8e08a n/a (/usr/lib/x86_64-linux-gnu/libc.so.6 + 0x2808a)
                #54 0x00007f3bc6e8e14b n/a (/usr/lib/x86_64-linux-gnu/libc.so.6 + 0x2814b)
                #55 0x0000559994d05545 n/a (/app/bin/valent + 0x2d545)
                ELF object binary architecture: AMD x86-64


`

**Comment by andyholmes** [comment]
Sorry, I've been busy lately :)

That's what I was looking for, although the debug symbols are missing, which is fine. You could retry with the `ca.andyholmes.Valent.Debug` (and maybe `org.gnome.Sdk.Debug`) packages installed, but it's a big download.

I will try and find time to look through and make a guess at what could have happened, possibly tomorrow.

**Comment by rohmishra** [comment]
I havent been able to reporoduce the error with debug version (...yet). Not really sure what caused this in the first time. Ill recreate a new issue in case i am ever able to reproduce it but closing this for now

**Comment by andyholmes** [comment]
Sounds good, thanks for checking back! It's certainly possible we just hit something that was fixed downstream :shrug:

The debug story is not great with Valent yet, since I didn't want to put debug stuff in the packet hot-path like with GSConnect. I'll try and think of something soon-ish, since I'd like to get this off the ground this cycle sometime.
