### ISSUE TITLE
Volume is decreased when receiving a phone call but does not return to its previous value once the phone call has ended. 

### ISSUE THREAD

**Issue by xusiai** [andyholmes/valent#612]
### Current Behavior

Valent lowers the volume when receiving a phone call (as expected) but does not increase it after the phone call has ended. 

### Expected Behavior

Volume returns to its previous value once a phone call has ended. 

### Desktop

Other (please specify)

### Other Desktop

Hyprland

### Operating System

NixOS 24.05

### Installed from

Distribution Package

### Version

1.0.0.alpha

### Devices

KDE Connect (Android), Valent (Desktop Linux)

### Plugins

PulseAudio

**Comment by andyholmes** [comment]
Thanks for the report, I guess this is probably related to #480.
