### ISSUE TITLE
mpris clients from Android are missing icons

### ISSUE THREAD

**Issue by orowith2os** [andyholmes/valent#630]
### Current Behavior

Any sort of media playing on my phone is missing the appropriate icon on GNOME (via Valent), despite it being there on Android. I've tested with YouTube, Crunchyroll, and Spotify.

### Expected Behavior

Icons would be transferred properly (albeit mangled, depending on context, like is done for icons in YouTube in Firefox or Chrome)

### Desktop

GNOME Shell

### Operating System

Fedora Rawhide

### Installed from

Nightly Flatpak

### Version

1.0.0.alpha

### Devices

KDE Connect (Android), Valent (Desktop Linux)

### Plugins

MPRIS

### Logs

```shell
{
  "application" : {
    "id" : "ca.andyholmes.Valent",
    "version" : "1.0.0.alpha",
    "commit" : "1e5cfd8"
  },
  "runtime" : {
    "os" : "GNOME 45 (Flatpak runtime)",
    "desktop" : "GNOME",
    "session" : "wayland",
    "environment" : "flatpak"
  },
  "plugins" : {
    "xdp" : true,
    "telephony" : true,
    "systemvolume" : true,
    "sms" : true,
    "share" : true,
    "sftp" : true,
    "runcommand" : true,
    "pulseaudio" : true,
    "presenter" : true,
    "ping" : true,
    "notification" : true,
    "mpris" : true,
    "mousepad" : true,
    "lock" : true,
    "libvalent-ui" : true,
    "libvalent-device" : true,
    "lan" : true,
    "gtk" : true,
    "gnome" : true,
    "findmyphone" : true,
    "fdo" : true,
    "eds" : true,
    "contacts" : true,
    "connectivity_report" : true,
    "clipboard" : true,
    "battery" : true
  }
}
```

### Screenshots

![image](https://github.com/andyholmes/valent/assets/93224879/8c6cf62f-64e1-4da3-b96c-c7146055783e)

**Comment by andyholmes** [comment]
Thanks for reporting :)

Valent should support transferring album art in both directions, although I think we only test in one direction (sort of).

For the Android side, see https://invent.kde.org/network/kdeconnect-android/-/merge_requests/353 which just needs some testing and review. The last time I built the MR it worked for the most part.

**Comment by orowith2os** [comment]
Actually, for some reason, media on my PC isn't showing in KDE Connect on my phone, so I'm curious as to why it won't work that way..........

Maybe me running it off mobile hotspot is affecting it.

**Comment by andyholmes** [comment]
> Actually, for some reason, media on my PC isn't showing in KDE Connect on my phone, period, so I'm curious as to why it won't work that way..........

Sometimes that happens for me, but no one else has complained so I assumed it was messy devenv.

If you can reproduce that (e.g. player started before/after Valent), that would be a good one.

**Comment by NaiveInvestigator** [comment]
> Actually, for some reason, media on my PC isn't showing in KDE Connect on my phone, period, so I'm curious as to why it won't work that way..........

I also. face this issue :0

**Comment by orowith2os** [comment]
> If you can reproduce that (e.g. player started before/after Valent), that would be a good one.

I believe I tried both situations, I'll file an issue later. I wasn't seeing much in the logs anyways.
