### ISSUE TITLE
MPRIS clients cannot be detected on-the-fly

### ISSUE THREAD

**Issue by 6b6279** [andyholmes/valent#655]
Hello,

when I start Valent, all the MPRIS clients that are present to the time of Valent's launch are correctly registered in the local remote and the KDE Connect client on my Android phone. But when I, for example, restart DeaDBeeF while Valent is running in background, it disappears from both remotes and doesn't re-appear when DeaDBeeF is running again. Restarting Valent always fixes the issue, but it's quite unhandy when I am, i.e., watching YouTube videos over mpv and then I have to restart Valent everytime mpv closes after a video finishes. `mpris-proxy` reports that `org.mpris.MediaPlayer2.DeaDBeeF` is present, so I doubt that the players I am using are communicating incorrectly with the event bus.

Volume control also seems to only sometimes work. I am on PipeWire, so I assume that there is no native PipeWire support yet.

Thanks.

### Expected Behavior

I expected Valent to regularly query `mpris-proxy` and see if any new MPRIS clients are introduced on-the-fly.

### Desktop

Other (please specify)

### Other Desktop

sway

### Operating System

Arch Linux

### Installed from

Nightly Flatpak

### Version

nightly

### Devices

KDE Connect (Android), Valent (Desktop Linux)

### Plugins

MPRIS remote plugin

### Logs

```shell
11:48:42.5657                       GLib-GIO:    DEBUG: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
11:48:42.5782                           GVFS:    DEBUG: org.gtk.vfs.MountTracker.listMountableInfo call failed: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gtk.vfs.Daemon was not provided by any .service files (g-dbus-error-quark, 2)

11:48:42.5782                       GLib-GIO:    DEBUG: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
11:48:42.5942                        Adwaita:    DEBUG: Setting org.freedesktop.appearance.contrast of type u not found
11:48:42.6159                       GLib-GIO:    DEBUG: _g_io_module_get_default: Found default implementation keyfile (GKeyfileSettingsBackend) for ‘gsettings-backend’
11:48:42.6167                       GLib-GIO:    DEBUG: _g_io_module_get_default: Found default implementation gnutls (GTlsBackendGnutls) for ‘gio-tls-backend’
11:48:42.6186                       GLib-GIO:    DEBUG: _g_io_module_get_default: Found default implementation portal (GNetworkMonitorPortal) for ‘gio-network-monitor’
11:48:42.6191                       GLib-GIO:    DEBUG: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
11:48:42.6790                       GLib-GIO:    DEBUG: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
11:48:42.8242                      libportal:    DEBUG: calling background
11:48:42.8248          valent-xdp-background:  WARNING: ValentXdpPlugin: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Background” on object at path /org/freedesktop/portal/desktop
11:48:43.7433       GVFS-RemoteVolumeMonitor:    DEBUG: Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gtk.vfs.Daemon was not provided by any .service files

11:48:43.7435                           GVFS:    DEBUG: cannot open directory /usr/share/gvfs/remote-volume-monitors: Error opening directory “/usr/share/gvfs/remote-volume-monitors”: No such file or directory
11:48:43.8035        valent-clipboard-plugin:    DEBUG: valent_clipboard_plugin_handle_clipboard_connect(): expected "content" field holding a string
11:48:43.8132                 valent-battery:    DEBUG: ValentBattery: not a battery

(valent:2): Gdk-WARNING **: 11:48:58.822: Compositor doesn't support moving popups, relying on remapping
```

**Comment by andyholmes** [comment]
Can you open a separate issue for volume control?

**Comment by 6b6279** [comment]
Whoa, thanks a lot for the very quick fix. I'll open an issue for the volume control "bug" right away. I already have `pipewire-pulse`, so I reckon it's having difficulties choosing which interface to use...?

**Comment by 6b6279** [comment]
After the fix for this issue, I haven't had any problems with volume control. Should the problem be resurgent, I'll open an issue for it.

**Comment by andyholmes** [comment]
Thanks, I do appreciate follow-ups! KDE Connect clients do a lot of stuff, so it can be hard to keep track of :slightly_smiling_face:
