### ISSUE TITLE
Messaging window does not update with sent messages

### ISSUE THREAD

**Issue by OsoRojo** [andyholmes/valent#656]
### Current Behavior

When sending a message from the Valent Messages UI, the message does not show in message history.  It IS sent through the mobile device and shows up properly in the UI on the mobile.  Must close and reopen the messages window for messages to show in the UI

When sending a message from the mobile device, the message does not appear in the Valent messages UI history, though the message is sent.  Must close and reopent the Valent Messages window to get it to behave as expected.

Note that Valent does not have to be quit entirely.  Closing and reopening the messages window seems to suffice.  

### Expected Behavior

Messages should properly propagate to the Valent Messages UI when sent, whether they are sent from the Valent Messages UI or from the mobile device without having to close and reopen the Messages window.  

### Desktop

GNOME Shell

### Operating System

Fedora 39

### Installed from

Nightly Flatpak

### Version

1.0.0.alpha

### Devices

KDE Connect (Android), KDE Connect (Desktop Linux)

**Comment by andyholmes** [comment]
This should be (mostly) fixed in the main branch now. There will be other related (and unrelated) issues though, as the plugin was entirely rewritten.

If you notice those, please open specific issues for each (this is a good template issue).
