### ISSUE TITLE
Find My Phone functionality unlocks desktop

### ISSUE THREAD

**Issue by ashrude** [andyholmes/valent#663]
### Current Behavior

If I lock my desktop then ring it using Find My Phone, the desktop unlocks.

### Expected Behavior

It should probably just play the ringing sound in the background and require the user to unlock the device to turn it off. This is what apple does - granted kde connect is for local networks.

### Desktop

GNOME Shell

### Operating System

Fedora 39

### Installed from

Nightly Flatpak

### Version

1.0.0.alpha

### Devices

Valent (Desktop Linux)

### Plugins

Find My Phone

**Comment by andyholmes** [comment]
I guess I did this on purpose, but it does seem like a security risk.

It would nice if there were a way to notify without unlocking, but best remove this for now.
