### ISSUE TITLE
kde connect android and valent don't see each other on wifi

### ISSUE THREAD

**Issue by 2-www** [andyholmes/valent#683]
### Current Behavior

i did:
:heavy_check_mark: connected to the same wifi network
:heavy_check_mark: `firewall-cmd --add-service=kdeconnect && firewall-cmd --reload` on the debian
:heavy_check_mark: opened the app on both devices at the same time

"Searching for devices..."

### Expected Behavior

the devies are displayed for each other

### Desktop

GNOME Shell

### Operating System

Debian testing

### Installed from

Built from source (Flatpak)

### Version

nightly

### Devices

KDE Connect (Android)

**Comment by andyholmes** [comment]
Any information you can provide? If not I will close this, as these are always local network issues.

**Comment by andyholmes** [comment]
Yeah, if you can't ping the device there's definitely something on your network. Maybe we should add a ping test when the UI for connecting to IP is added :thinking:

**Comment by pakosaan** [comment]
I can ping to my android  but still it cannot detect my android  but the  my android and valent both can see another device

**Comment by andyholmes** [comment]
Hi, you can find logs for Valent using `journalctl` (or GNOME Logs). Additionally, if you have `adb` setup you can run this command locally:

```sh
adb logcat --pid=$(adb shell pidof -s org.kde.kdeconnect_tp)
```

If the desktop is also running Fedora, you might want to check `firewalld` is set to the correct zone. It ships with configuration for KDE Connect, but I think it's normally only enabled for the default zone.
