### ISSUE TITLE
Remote input not working

### ISSUE THREAD

**Issue by hir0xygen** [andyholmes/valent#720]
### Current Behavior

Remote input is not received by the computer.

### Expected Behavior

I can move my mouse using my phone as touchpad and type with my phones keyboard.

### Desktop

Cinnamon

### Operating System

Artix Linux

### Installed from

Built from source (Other)

### Version

1.0.0.alpha

### Logs

```shell
00:54:02.4173               valent-xdp-input:  WARNING: on_session_created(): GDBus.Error:org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.ScreenCast”
```

**Comment by hir0xygen** [comment]
Note that it works just fine when using KDE Connect on desktop, but using Valent it doesn't work.

**Comment by andyholmes** [comment]
Thanks for the logs.

I removed the screencast flag since we don't use it currently, so as long as your distro support the regular mouse/keyboard portal it should work now.
