### ISSUE TITLE
Remote control request

### ISSUE THREAD

**Issue by zachvlat** [andyholmes/valent#721]
### Current Behavior

![Screenshot_20240823_101918](https://github.com/user-attachments/assets/dc380671-27a8-48b1-95ff-920b18088c87)

As you can see on screenshot, on KDE Plasma 5.27 (flatpak) I am always asked to share my mouse, every time. Is this something that can be fixed with flatpak or system permissions?

### Expected Behavior

Press Share and the permission stays.

### Desktop

Other (please specify)

### Other Desktop

KDE Plasma 5.27

### Operating System

Debian 12

### Installed from

Nightly Flatpak

### Version

nightly

**Comment by andyholmes** [comment]
Thanks for the report.

I updated libportal in the Flatpak and meson wrap to the `main` branch, so the new persistence option should work automatically after an update. However, if someone builds it as a distro package or something, it may link to a system library and that particular feature won't work.
