### ISSUE TITLE
gvc subproject not included in release tarball

### ISSUE THREAD

**Issue by werdahias** [andyholmes/valent#734]
### Current Behavior

-

### Expected Behavior

the gvc tarball should be included in the tarball release

### Desktop

Other (please specify)

### Other Desktop

sway

### Operating System

Debian sid

### Installed from

Built from source (Other)

### Version

1.0.0.alpha

### Logs

```shell
n/a
```

**Comment by andyholmes** [comment]
Do you mean for 1.0.0.alpha.46?

**Comment by andyholmes** [comment]
I've uploaded a dist release for [1.0.0.alpha.46](https://github.com/andyholmes/valent/releases/tag/v1.0.0.alpha.46), hopefully that's what you meant.

**Comment by werdahias** [comment]
yes, thanks
