### ISSUE TITLE
Double free at startup on ubuntu 22.04.

### ISSUE THREAD

**Issue by 17steen** [andyholmes/valent#754]
### Current Behavior

Crashes at startup after having opened the window for around one second.

flatpak run ca.andyholmes.Valent 
11:28:51.2654                       GLib-GIO:    DEBUG: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
11:28:51.2684                       GLib-GIO:    DEBUG: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
11:28:51.2814                        Adwaita:    DEBUG: Setting org.freedesktop.appearance.contrast of type u not found
11:28:51.2826                        Adwaita:    DEBUG: Setting org.freedesktop.appearance.accent-color of type (ddd) not found
11:28:51.3016                       GLib-GIO:    DEBUG: _g_io_module_get_default: Found default implementation keyfile (GKeyfileSettingsBackend) for ‘gsettings-backend’
11:28:51.3022                       GLib-GIO:    DEBUG: _g_io_module_get_default: Found default implementation gnutls (GTlsBackendGnutls) for ‘gio-tls-backend’
11:28:51.3036                       GLib-GIO:    DEBUG: _g_io_module_get_default: Found default implementation portal (GNetworkMonitorPortal) for ‘gio-network-monitor’
11:28:51.3041                       GLib-GIO:    DEBUG: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
11:28:51.3062                       GLib-GIO:    DEBUG: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
11:28:52.0334                      libportal:    DEBUG: calling background
11:28:52.7633                        Tracker:    DEBUG: Current and DB locales match: 'fr_BE.UTF-8'
11:28:52.7834                        Tracker:    DEBUG: Current and DB locales match: 'fr_BE.UTF-8'
11:28:52.8065                        Tracker:    DEBUG: Current and DB locales match: 'fr_BE.UTF-8'
11:28:52.8166        valent-messages-adapter:  WARNING: cursor_get_threads_cb(): database disk image is malformed
11:28:52.9305              valent-sms-device:  WARNING: valent_sms_device_get_timestamp_cb(): database disk image is malformed
double free or corruption (fasttop)

### Expected Behavior

I expect the program to startup normally.

### Desktop

GNOME Shell

### Operating System

Ubuntu 22.04

### Installed from

Nightly Flatpak

### Version

nightly

### Devices

KDE Connect (Android)

### Logs

```shell
flatpak run ca.andyholmes.Valent 
11:28:51.2654                       GLib-GIO:    DEBUG: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
11:28:51.2684                       GLib-GIO:    DEBUG: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
11:28:51.2814                        Adwaita:    DEBUG: Setting org.freedesktop.appearance.contrast of type u not found
11:28:51.2826                        Adwaita:    DEBUG: Setting org.freedesktop.appearance.accent-color of type (ddd) not found
11:28:51.3016                       GLib-GIO:    DEBUG: _g_io_module_get_default: Found default implementation keyfile (GKeyfileSettingsBackend) for ‘gsettings-backend’
11:28:51.3022                       GLib-GIO:    DEBUG: _g_io_module_get_default: Found default implementation gnutls (GTlsBackendGnutls) for ‘gio-tls-backend’
11:28:51.3036                       GLib-GIO:    DEBUG: _g_io_module_get_default: Found default implementation portal (GNetworkMonitorPortal) for ‘gio-network-monitor’
11:28:51.3041                       GLib-GIO:    DEBUG: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
11:28:51.3062                       GLib-GIO:    DEBUG: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
11:28:52.0334                      libportal:    DEBUG: calling background
11:28:52.7633                        Tracker:    DEBUG: Current and DB locales match: 'fr_BE.UTF-8'
11:28:52.7834                        Tracker:    DEBUG: Current and DB locales match: 'fr_BE.UTF-8'
11:28:52.8065                        Tracker:    DEBUG: Current and DB locales match: 'fr_BE.UTF-8'
11:28:52.8166        valent-messages-adapter:  WARNING: cursor_get_threads_cb(): database disk image is malformed
11:28:52.9305              valent-sms-device:  WARNING: valent_sms_device_get_timestamp_cb(): database disk image is malformed
double free or corruption (fasttop)
```

**Comment by andyholmes** [comment]
This is likely a duplicate of #742. Try clearing your cache in these cases, as the database format will change fairly often.
